staging/zotero-libreoffice-integration/chrome*		usr/share/xul-ext/libreoffice-zotero-integration/
staging/zotero-libreoffice-integration/defaults		usr/share/xul-ext/libreoffice-zotero-integration/
staging/zotero-libreoffice-integration/resource		usr/share/xul-ext/libreoffice-zotero-integration/
staging/zotero-libreoffice-integration/components	usr/share/xul-ext/libreoffice-zotero-integration/
staging/zotero-libreoffice-integration/install.rdf		usr/share/xul-ext/libreoffice-zotero-integration/
staging/zotero-libreoffice-integration/build/oxt/*	usr/lib/libreoffice/share/extensions/Zotero_OpenOffice_Integration/
